In [7]:
import pandas as pd

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
df = pd.read_csv("/content/bios.csv")

In [10]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.shape

(145500, 16)

In [12]:
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name',
       'Name order'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  object
 1   Sex            145500 non-null  object
 2   Full name      145500 non-null  object
 3   Used name      145500 non-null  object
 4   Born           143772 non-null  object
 5   Died           34042 non-null   object
 6   NOC            145499 non-null  object
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  object
 9   Affiliations   95832 non-null   object
 10  Nick/petnames  9145 non-null    object
 11  Title(s)       399 non-null     object
 12  Other names    7167 non-null    object
 13  Nationality    8259 non-null    object
 14  Original name  30739 non-null   object
 15  Name order     7844 non-null    object
dtypes: int64(1), object(15)
memory usage: 17.8+ MB

In [14]:
df.isna().sum()

Roles                 0
Sex                   0
Full name             0
Used name             0
Born               1728
Died             111458
NOC                   1
athlete_id            0
Measurements      37667
Affiliations      49668
Nick/petnames    136355
Title(s)         145101
Other names      138333
Nationality      137241
Original name    114761
Name order       137656
dtype: int64

In [15]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

Removing Dot '•' from the Used Names

In [16]:
df["Used name"] = (
    df["Used name"]
      .astype(str) #Converts every value in the column to a Python string.
      .str.replace(r"[•·‧]", " ", regex=True) #Replaces any occurrence of these characters:[•·‧] " " replaces each matched character with a single space
      .str.strip()#Removes leading and trailing whitespace from each string.
)

In [17]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

Adding Spaces Between Names and string them in new column "display_name"

In [21]:
df["display_name"] = (
    df["Used name"]
    .astype(str)
    .str.replace(r"[•·‧]", "", regex=True)
    .str.replace(r"([A-Z])([a-z])",r"\1 \2", regex=True)
    .str.strip()
)

In [22]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,display_name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J ean-F rançois B lanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,A rnaud B oetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,J ean B orotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,J acques B rugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,A lbert C anet

In [23]:
df["Used name"].str.contains("•", regex=False, na=False).sum()

np.int64(0)

In [24]:
df["Used name"].str.contains("•").sum()

np.int64(0)

Cleaning Measurements

Part	Meaning
(\d+)	one or more digits → height
\s*	optional spaces
cm	literal unit
/	separator
(\d+)	one or more digits → weight
kg	literal unit

In [25]:
df[["height_cm","weight_kg"]]=(
    df["Measurements"].str.extract(r"(\d+)\s*cm\s*/\s*(\d+)\s*kg")
)

In [26]:
df[["Measurements","height_cm","weight_kg"]].head(10)

     Measurements height_cm weight_kg
0             NaN       NaN       NaN
1  183 cm / 76 kg       183        76
2  183 cm / 76 kg       183        76
3  168 cm / 64 kg       168        64
4             NaN       NaN       NaN
5  181 cm / 70 kg       181        70
6  180 cm / 73 kg       180        73
7             NaN       NaN       NaN
8             NaN       NaN       NaN
9             NaN       NaN       NaN

Converting height_cm and weight_kg to numeric

In [27]:
df['height_cm'] = pd.to_numeric(df['height_cm'], errors="coerce")
df['weight_kg'] = pd.to_numeric(df['weight_kg'], errors="coerce")

In [28]:
df[['height_cm', 'weight_kg']].dtypes

height_cm    float64
weight_kg    float64
dtype: object

Validate height_cm and weight_kg ranges

In [30]:
df.loc[~df['height_cm'].between(120, 250), "height_cm"] = pd.NA
df.loc[~df['weight_kg'].between(30, 250), "weight_kg"] = pd.NA

In [31]:
df[["height_cm", "weight_kg"]].isna().sum()

height_cm    43430
weight_kg    43434
dtype: int64

In [32]:
df[["height_cm", "weight_kg"]].describe()

           height_cm      weight_kg
count  102070.000000  102066.000000
mean      176.334780      71.892746
std        10.379696      14.463121
min       127.000000      30.000000
25%       170.000000      62.000000
50%       176.000000      70.000000
75%       183.000000      80.000000
max       226.000000     198.000000

Cleaning the Born column, Extracting the Date String

In [35]:
#June 30, 1985
#21 August 1986
#1997-03-14
born_extracted = df['Born'].str.extract(
    r"([A-Za-z]+\s+\d{1,2},\s+\d{4}|\d{1,2}+\s+[A-Za-z]+\s+\d{4}|\d{4}-\d{2}-\d{2})")

Convert extracted birth date text to datetime

In [36]:
df["born_date"] = pd.to_datetime(born_extracted[0], errors="coerce")

In [37]:
df[["Born", "born_date"]].head(10)

                                                Born  born_date
0        12 December 1886 in Bordeaux, Gironde (FRA) 1886-12-12
1             1 April 1969 in Meulan, Yvelines (FRA) 1969-04-01
2  13 August 1898 in Biarritz, Pyrénées-Atlantiqu... 1898-08-13
3            11 May 1895 in Paris VIIIe, Paris (FRA) 1895-05-11
4         17 April 1878 in Wandsworth, England (GBR) 1878-04-17
5             13 January 1970 in Amiens, Somme (FRA) 1970-01-13
6     27 November 1969 in Ris-Orangis, Essonne (FRA) 1969-11-27
7      14 December 1901 in Villeurbanne, Rhône (FRA) 1901-12-14
8                 4 August 1896 in Nîmes, Gard (FRA) 1896-08-04
9      16 July 1868 in Farges-Allichamps, Cher (FRA) 1868-07-16

In [38]:
df["born_date"].dtype

dtype('<M8[ns]')

Extract birth location (city / region / country)

In [39]:
location_extracted = df["Born"].str.extract(
    r"in\s+([^,]+),\s*([^()]+)\s*\(([^)]+)\)"
)

#1)in\s+
#Match the word in followed by space
#1)([^,]+)
#→ City
#Everything up to first comma
#3),\s*
#Comma + optional space
#4)([^()]+)
#→ Region
#Everything up to (
#5)\(([^)]+)\)
#→ Country
#Text inside parentheses

Assign to meaningful column names

In [40]:
df[["birth_city", "birth_region", "birth_country"]] = location_extracted

Then clean whitespace:

In [41]:
for col in ['birth_city','birth_region','birth_country']:
  df[col] = df[col].str.strip()

In [42]:
df[["Born", "birth_city", "birth_region", "birth_country"]].head(10)

,Born,birth_city,birth_region,birth_country
0,"12 December 1886 in Bordeaux, Gironde (FRA)",Bordeaux,Gironde,FRA
1,"1 April 1969 in Meulan, Yvelines (FRA)",Meulan,Yvelines,FRA
2,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...",Biarritz,Pyrénées-Atlantiques,FRA
3,"11 May 1895 in Paris VIIIe, Paris (FRA)",Paris VIIIe,Paris,FRA
4,"17 April 1878 in Wandsworth, England (GBR)",Wandsworth,England,GBR
5,"13 January 1970 in Amiens, Somme (FRA)",Amiens,Somme,FRA
6,"27 November 1969 in Ris-Orangis, Essonne (FRA)",Ris-Orangis,Essonne,FRA
7,"14 December 1901 in Villeurbanne, Rhône (FRA)",Villeurbanne,Rhône,FRA
8,"4 August 1896 in Nîmes, Gard (FRA)",Nîmes,Gard,FRA
9,"16 July 1868 in Farges-Allichamps, Cher (FRA)",Farges-Allichamps,Cher,FRA

Born column drop

In [43]:
df.drop(columns=["Born"], inplace=True)

In [44]:
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Died', 'NOC', 'athlete_id',
       'Measurements', 'Affiliations', 'Nick/petnames', 'Title(s)',
       'Other names', 'Nationality', 'Original name', 'Name order',
       'display_name', 'height_cm', 'weight_kg', 'born_date', 'birth_city',
       'birth_region', 'birth_country'],
      dtype='object')

Cleaning the Died column

In [45]:
df["Died"].head()

0    2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...
1                                                  NaN
2    17 July 1994 in Arbonne, Pyrénées-Atlantiques ...
3                20 March 1978 in Monaco, Monaco (MON)
4              25 July 1930 in Paris VIIe, Paris (FRA)
Name: Died, dtype: object

In [46]:
died_extracted = df["Died"].str.extract(
    r"([A-Za-z]+\s+\d{1,2},\s+\d{4}|\d{1,2}\s+[A-Za-z]+\s+\d{4}|\d{4}-\d{2}-\d{2})"
)

In [47]:
df["died_date"] = pd.to_datetime(died_extracted[0], errors="coerce")

In [48]:
df[["Died", "died_date"]].head(10)

                                                Died  died_date
0  2 October 1960 in Saint-Jean-de-Luz, Pyrénées-... 1960-10-02
1                                                NaN        NaT
2  17 July 1994 in Arbonne, Pyrénées-Atlantiques ... 1994-07-17
3              20 March 1978 in Monaco, Monaco (MON) 1978-03-20
4            25 July 1930 in Paris VIIe, Paris (FRA) 1930-07-25
5                                                NaN        NaT
6                                                NaN        NaT
7  2 April 1987 in Saint-Germain-en-Laye, Yveline... 1987-04-02
8                 1 August 1986 in Nîmes, Gard (FRA) 1986-08-01
9                                     27 August 1923 1923-08-27

Extract death location

In [49]:
death_location = df["Died"].str.extract(
    r"in\s+([^,]+),\s*([^()]+)\s*\(([^)]+)\)"
)
#1)in\s+
#Match the word in followed by space
#1)([^,]+)
#→ City
#Everything up to first comma
#3),\s*
#Comma + optional space
#4)([^()]+)
#→ Region
#Everything up to (
#5)\(([^)]+)\)
#→ Country
#Text inside parentheses

Extract death location (city / region / country)

In [50]:
df[["death_city", "death_region", "death_country"]] = death_location

Then Clean Whitespace

In [51]:
for col in ['death_city','death_region','death_country']:
  df[col] = df[col].str.strip()

In [52]:
df[["Died", "death_city", "death_region", "death_country"]].head(10)

,Died,death_city,death_region,death_country
0,"2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",Saint-Jean-de-Luz,Pyrénées-Atlantiques,FRA
1,NaN,NaN,NaN,NaN
2,"17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",Arbonne,Pyrénées-Atlantiques,FRA
3,"20 March 1978 in Monaco, Monaco (MON)",Monaco,Monaco,MON
4,"25 July 1930 in Paris VIIe, Paris (FRA)",Paris VIIe,Paris,FRA
5,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN
7,"2 April 1987 in Saint-Germain-en-Laye, Yveline...",Saint-Germain-en-Laye,Yvelines,FRA
8,"1 August 1986 in Nîmes, Gard (FRA)",Nîmes,Gard,FRA
9,27 August 1923,NaN,NaN,NaN

In [53]:
df.drop(columns=["Died"], inplace=True)

Cleaning Affiliations

In [54]:
aff_extracted = df["Affiliations"].str.extract(
    r"^([^,]+),\s*([^()]+)\s*\(([^)]+)\)$"
)

Assign extracted values

In [55]:

df[["affiliation_name", "affiliation_city", "affiliation_country"]] = aff_extracted

Clean whitespace (only this)

In [56]:
for col in ["affiliation_name", "affiliation_city", "affiliation_country"]:
    df[col] = df[col].str.strip()

In [57]:
df[["Affiliations", "affiliation_name", "affiliation_city", "affiliation_country"]].head(10)

,Affiliations,affiliation_name,affiliation_city,affiliation_country
0,NaN,NaN,NaN,NaN
1,"Racing Club de France, Paris (FRA)",Racing Club de France,Paris,FRA
2,"TCP, Paris (FRA)",TCP,Paris,FRA
3,"Sporting club de Paris, Paris (FRA)",Sporting club de Paris,Paris,FRA
4,"TCP, Paris (FRA)",TCP,Paris,FRA
5,"SAG Cestas, Cestas (FRA)",SAG Cestas,Cestas,FRA
6,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",NaN,NaN,NaN
7,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN

Country Normalization — FRA → France (and others)

In [58]:
pd.concat([
    df["birth_country"],
    df["death_country"],
    df["affiliation_country"]
]).dropna().unique()

array(['FRA', 'GBR', 'MAR', 'FPN', 'IRQ', 'USA', 'RSA', 'IRL', 'IND',
       'CHN', 'JAM', 'AUS', 'CAN', 'GER', 'ROU', 'BRA', 'CZE', 'RUS',
       'GRE', 'EGY', 'HUN', 'POL', 'MEX', 'SRB', 'SVK', 'INA', 'SRI',
       'PAK', 'ESP', 'AUT', 'BEL', 'BLR', 'BUL', 'CRC', 'DEN', 'EST',
       'FIN', 'SUI', 'GEO', 'ARG', 'ARM', 'BAH', 'CAM', 'CHI', 'ISR',
       'UZB', 'ITA', 'JPN', 'KOR', 'LAT', 'UKR', 'LTU', 'LUX', 'MAD',
       'MAS', 'MRI', 'NED', 'NGR', 'NOR', 'TUR', 'NZL', 'PAR', 'PER',
       'BAR', 'HKG', 'GUY', 'CGO', 'COD', 'CMR', 'COL', 'PUR', 'TPE',
       'VIE', 'CUB', 'DOM', 'CRO', 'ECU', 'ESA', 'MDA', 'MGL', 'ZIM',
       'PHI', 'POR', 'SLO', 'SWE', 'TJK', 'CIV', 'BIH', 'THA', 'CAF',
       'ALG', 'PRK', 'KAZ', 'UGA', 'TTO', 'TUN', 'AZE', 'URU', 'MYA',
       'VEN', 'ETH', 'FIJ', 'SEN', 'LBA', 'GAB', 'NCA', 'CUR', 'ARU',
       'ANG', 'ANT', 'Cologne', 'KOS', 'GHA', 'GUA', 'TLS', 'NEP', 'IRI',
       'ISV', 'SKN', 'KEN', 'KGZ', 'LBR', 'MAW', 'MLI', 'NAM', 'CPV',
       'SUR', 'AGU', 'SLE', 'NIG', 'SAM', 'PAN', 'TKM', 'MKD', 'SGP',
       'MNE', 'SYR', 'MON', 'PNG', 'BEN', 'ZAM', 'SUD', 'SSD', 'BDI',
       'TAN', 'TGA', 'VAN', 'BOL', 'MLT', 'JER', 'KSA', 'MOZ', 'BER',
       'GRL', 'LBN', 'CYP', 'SMR', 'ERI', 'LIE', 'GUM', 'BIZ', 'CAY',
       'ALB', 'AND', 'Spreewald', 'MTS', 'HAI', 'IOM', 'FLI', 'MAC',
       'BAN', 'Vienna', 'NCD', 'GUI', 'KUW', 'STP', 'GBS', 'QAT', 'SOM',
       'TOG', 'Elster', 'ISL', 'GUE', 'Saale', 'Milde', 'GIB', 'BUR',
       'JOR', 'OMA', 'NFI', 'BRN', 'YEM', 'DMA', 'GEQ', 'HON', 'SWZ',
       'Prignitz', 'KIR', 'COK', 'NRU', 'AFG', 'Altmark', 'Munich', 'IVB',
       'BOT', 'VIN', 'CHA', 'COM', 'DJI', 'MRT', 'WAF', 'MQE', 'GAM',
       'SEY', 'Havel', 'Luppe', 'GRN', 'LCA', 'PLE', 'RWA', 'SOL', 'ASA',
       'BHU', 'Upland', 'SMT', 'SPM', 'FSM', 'PLW', 'LES', 'UAE', 'TKS',
       'MDV', 'LAO', 'MHL', 'TUV', 'FAR', 'BRU', 'MTN', 'Corfu', 'Aarhus',
       'Aller', 'Southern Philippines', 'Ypres', 'HEL', 'MIX', 'HCAW',
       'TTT', 'ADO', 'Alma-Ata', '08', 'SCHC', 'HGC', 'Cairo', '96',
       'TCH', '92', '00', 'NMI', 'DWK', 'PSV', 'Leningrad', '84', 'AMVJ',
       'Central Sport Klub Army', "CIKO '66", "ATC '75", 'PAC', 'V&L',
       'CUNY', "AV '34", 'Toledo', 'GDP', 'LIB'], dtype=object)

In [59]:
country_map = {
    "FRA": "France",
    "GBR": "United Kingdom",
    "USA": "United States",
    "GER": "Germany",
    "ITA": "Italy",
    "ESP": "Spain"
}

In [60]:
for col in ["birth_country", "death_country", "affiliation_country"]:
    df[col] = df[col].map(country_map)

In [61]:
df[["birth_country", "death_country", "affiliation_country"]].head(10)

    birth_country death_country affiliation_country
0          France        France                 NaN
1          France           NaN              France
2          France        France              France
3          France           NaN              France
4  United Kingdom        France              France
5          France           NaN              France
6          France           NaN                 NaN
7          France        France                 NaN
8          France        France                 NaN
9          France           NaN                 NaN

In [ ]:
(df["died_date"].fillna(pd.Timestamp.today()) - df["born_date"]).dt.days // 365

Saving File in Parquet

In [ ]:
df.to_parquet(
    "olympic_athletes_clean.parquet",
    engine="pyarrow",
    index=False
)

Export to CSV (SECONDARY format)
Why CSV

Human-readable

Universal

Easy sharing

In [62]:
df.to_csv(
    "olympic_athletes_clean.csv",
    index=False
)

In [63]:
df.dtypes.to_csv("olympic_athletes_schema.csv")

GROUPBY — EXPLAINED
“How many athletes are there per birth country?”

In [64]:
df.groupby("birth_country").size().reset_index(name="athlete_count")

    birth_country  athlete_count
0          France           5391
1         Germany           7526
2           Italy           4916
3           Spain           2719
4  United Kingdom           6023
5   United States          10101

Average height per country

In [65]:
df.groupby("birth_country")["height_cm"].mean()

birth_country
France            176.563236
Germany           178.580618
Italy             176.637708
Spain             176.029837
United Kingdom    176.599887
United States     178.368380
Name: height_cm, dtype: float64

Multiple calculations at once (aggregation)

In [66]:
df.groupby("birth_country").agg(
    athlete_count = ("athlete_id","size"),
    avg_height_cm = ("height_cm", "mean")
).reset_index

<bound method DataFrame.reset_index of                 athlete_count  avg_height_cm
birth_country
France                   5391     176.563236
Germany                  7526     178.580618
Italy                    4916     176.637708
Spain                    2719     176.029837
United Kingdom           6023     176.599887
United States           10101     178.368380>

Group by TWO columns

In [70]:
df.groupby(["birth_country", "Sex"]).size()

birth_country   Sex
France          Female    1169
                Male      4222
Germany         Female    2261
                Male      5265
Italy           Female    1151
                Male      3765
Spain           Female     692
                Male      2027
United Kingdom  Female    1603
                Male      4420
United States   Female    3028
                Male      7073
dtype: int64

Checking Data type of born_year

In [85]:
df["born_date"].dtype

dtype('<M8[ns]')

Setting Index to Born Date

In [87]:
#df = df.reset_index()
#df = df.set_index("born_date")
df.index.name

'born_date'

Athletes born per year

In [80]:
df.resample("Y").size().reset_index(name = "Athlete_count")

/tmp/ipython-input-527114226.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df.resample("Y").size().reset_index(name = "Athlete_count")

     born_date  Athlete_count
0   1828-12-31              1
1   1829-12-31              0
2   1830-12-31              0
3   1831-12-31              2
4   1832-12-31              0
..         ...            ...
177 2005-12-31            163
178 2006-12-31             17
179 2007-12-31              3
180 2008-12-31              3
181 2009-12-31              1

[182 rows x 2 columns]

In [74]:
df.resample("Y").size()

/tmp/ipython-input-3607429006.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df.resample("Y").size()

born_date
1828-12-31      1
1829-12-31      0
1830-12-31      0
1831-12-31      2
1832-12-31      0
             ...
2005-12-31    163
2006-12-31     17
2007-12-31      3
2008-12-31      3
2009-12-31      1
Length: 182, dtype: int64

Decade grouping

In [79]:
df.resample("10Y").size().reset_index(name="athlete_count")

/tmp/ipython-input-2806293755.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df.resample("10Y").size().reset_index(name="athlete_count")

    born_date  athlete_count
0  1828-12-31              1
1  1838-12-31              6
2  1848-12-31             30
3  1858-12-31            130
4  1868-12-31            409
5  1878-12-31           1328
6  1888-12-31           3372
7  1898-12-31           3513
8  1908-12-31           5062
9  1918-12-31           5151
10 1928-12-31           5868
11 1938-12-31           9252
12 1948-12-31          11985
13 1958-12-31          13419
14 1968-12-31          18600
15 1978-12-31          21184
16 1988-12-31          20913
17 1998-12-31          17211
18 2008-12-31           4250
19 2018-12-31              1

MutiIndexing - Creting Mutiple Index

In [88]:
df.groupby(["birth_country", "Sex"]) \
  .size() \
  .reset_index(name="athlete_count")

     birth_country     Sex  athlete_count
0           France  Female           1169
1           France    Male           4222
2          Germany  Female           2261
3          Germany    Male           5265
4            Italy  Female           1151
5            Italy    Male           3765
6            Spain  Female            692
7            Spain    Male           2027
8   United Kingdom  Female           1603
9   United Kingdom    Male           4420
10   United States  Female           3028
11   United States    Male           7073